baseURL: /
googleAnalytics: G-V8WJDERTX9
copyright: Dave Gallant
title: davegallant.ca
enableGitInfo: true
enableRobotsTXT: true
noJSConfigInAssets: true

params:
  author: Dave Gallant
  subtitle: blog

  logo:
    text: davegallant.ca
    url: /

  defaultTheme: "dark"

  comments:
    utterances:
      enable: true
      issueTerm: "pathname"
      github:
        username: davegallant
        repository: site

  prism:
    plugins:
      - normalize-whitespace
      - toolbar
      - copy-to-clipboard
      - command-line

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3

permalinks:
  post: "/blog/:year/:month/:day/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: hugo-theme-gruvbox
  mounts:
    - source: node_modules/simple-icons/icons
      target: assets/simple-icons
    - source: assets
      target: assets
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: node_modules/prismjs
      target: assets/prismjs
    - source: node_modules/prism-themes/themes
      target: assets/prism-themes
    - source: node_modules/typeface-fira-code/files
      target: static/fonts
    - source: node_modules/typeface-roboto-slab/files
      target: static/fonts
    - source: node_modules/@tabler/icons/icons
      target: assets/tabler-icons
