baseurl: /
staticDir: static
languageCode: en-us
googleAnalytics: G-V8WJDERTX9
copyright: Dave Gallant
preserveTaxonomyNames: true
pygmentsstyle: nord
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
theme:
  - archie
  - hugo-video
title: davegallant

params:
    mode: toggle
    useCDN: true
    subtitle: "A personal blog"
    mathjax: true
    katex: true 

    favicon: https://davegallant.ca/favicon.ico

    kofi: 

    customcss:
      - css/custom.css

    social:
      - name: Email
        icon: at-sign
        url: 'mailto:me@davegallant.ca'
      - name: LinkTree
        icon: compass
        url: 'https://linktr.ee/davegallant'
      - name: GitHub
        icon: github
        url: 'https://github.com/davegallant'
      - name: Mastodon
        icon: speaker
        url: https://mastodon.social/@davegallant
      - name: LinkedIn
        icon: linkedin
        url: https://www.linkedin.com/in/dave-gallant/

    comments:
      utterances:
        enable: true
        issueTerm: "pathname"
        github:
          username: davegallant
          repository: davegallant.github.io

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3

permalinks:
  post: '/blog/:year/:month/:day/:slug/'
