baseURL: /
copyright: Dave Gallant
title: davegallant.ca
enableGitInfo: true
enableRobotsTXT: true
paginate: 20

services:
  googleAnalytics:
    ID: G-V8WJDERTX9

build:
  noJSConfigInAssets: true
  writeStats: true

params:
  author: Dave Gallant
  subtitle:
  description: "Dave Gallant is a software developer and a computer enthusiast."

  logo:
    text: davegallant.ca
    url: /

  defaultTheme: "dark"

  comments:
    utterances:
      enable: true
      issueTerm: "pathname"
      github:
        username: davegallant
        repository: site

  prism:
    languages:
      - markup
      - css
      - clike
      - javascript
      - bash
      - csharp
      - hcl
      - ignore
      - json
      - markdown
      - powershell
      - toml
      - yaml
    plugins:
      - normalize-whitespace
      - toolbar
      - copy-to-clipboard
      - command-line

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog
      weight: 2

permalinks:
  post: "/blog/:year/:month/:day/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: hugo-theme-gruvbox
  mounts:
    - source: node_modules/simple-icons/icons
      target: assets/simple-icons
    - source: assets
      target: assets
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: node_modules/prismjs
      target: assets/prismjs
    - source: node_modules/prism-themes/themes
      target: assets/prism-themes
    - source: node_modules/typeface-fira-code/files
      target: static/fonts
    - source: node_modules/typeface-roboto-slab/files
      target: static/fonts
    - source: node_modules/@tabler/icons/icons
      target: assets/tabler-icons
