baseurl: /
staticDir: static
languageCode: en-us
googleAnalytics: UA-98710982-2
copyright: Dave Gallant
preserveTaxonomyNames: true
pygmentsstyle: "monokai"
pygmentscodefences:  true
pygmentscodefencesguesssyntax: true
theme: archie
title: davegallant

params:
    mode: toggle
    useCDN: true
    subtitle: "A personal blog about technical discovery"
    mathjax: true
    katex: true 

    favicon: https://davegallant.ca/favicon.ico

    customcss:
      - css/custom.css

    social:
      - name: GitHub
        icon: github
        url: 'https://github.com/davegallant'
      - name: Twitter
        icon: twitter
        url: 'https://twitter.com/davega11ant/'
      - name: Mastodon
        icon: speaker
        url: https://fosstodon.org/@davegallant
      - name: LinkedIn
        icon: linkedin
        url: https://www.linkedin.com/in/dave-gallant/

    comments:
      utterances:
        enable: true
        issueTerm: "pathname"
        github:
          username: davegallant
          repository: davegallant.github.io

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /post
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4

permalinks:
  post: '/blog/:year/:month/:day/:slug/'
